# Generated by Django 3.2.7 on 2021-09-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexyyapp', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
